// Menu items data
const menuItems = [
  {
    id: "1",
    name: "Masala Dosa",
    description: "Crispy rice crepe filled with spiced potato filling, served with sambar and chutney",
    price: 80,
    category: "Breakfast",
    image: "/placeholder.svg?height=300&width=400&text=Masala+Dosa",
    vegetarian: true,
    featured: true,
  },
  {
    id: "2",
    name: "Idli Sambar",
    description: "Steamed rice cakes served with lentil soup and coconut chutney",
    price: 60,
    category: "Breakfast",
    image: "/placeholder.svg?height=300&width=400&text=Idli+Sambar",
    vegetarian: true,
    featured: false,
  },
  {
    id: "3",
    name: "Poha",
    description: "Flattened rice cooked with onions, peanuts, and spices",
    price: 40,
    category: "Breakfast",
    image: "/placeholder.svg?height=300&width=400&text=Poha",
    vegetarian: true,
    featured: false,
  },
  {
    id: "4",
    name: "Vada Pav",
    description: "Spicy potato fritter in a bun with chutneys",
    price: 30,
    category: "Snacks",
    image: "/placeholder.svg?height=300&width=400&text=Vada+Pav",
    vegetarian: true,
    featured: true,
  },
  {
    id: "5",
    name: "Thali",
    description: "Complete meal with rice, dal, vegetables, roti, and dessert",
    price: 120,
    category: "Lunch",
    image: "/placeholder.svg?height=300&width=400&text=Thali",
    vegetarian: true,
    featured: true,
  },
  {
    id: "6",
    name: "Paneer Butter Masala",
    description: "Cottage cheese cubes in rich tomato gravy",
    price: 140,
    category: "Lunch",
    image: "/placeholder.svg?height=300&width=400&text=Paneer+Butter+Masala",
    vegetarian: true,
    featured: false,
  },
  {
    id: "7",
    name: "Chicken Biryani",
    description: "Fragrant rice cooked with chicken and aromatic spices",
    price: 160,
    category: "Lunch",
    image: "/placeholder.svg?height=300&width=400&text=Chicken+Biryani",
    vegetarian: false,
    featured: true,
  },
  {
    id: "8",
    name: "Samosa",
    description: "Crispy pastry filled with spiced potatoes and peas",
    price: 20,
    category: "Snacks",
    image: "/placeholder.svg?height=300&width=400&text=Samosa",
    vegetarian: true,
    featured: false,
  },
  {
    id: "9",
    name: "Pav Bhaji",
    description: "Spiced vegetable mash served with buttered bread rolls",
    price: 70,
    category: "Snacks",
    image: "/placeholder.svg?height=300&width=400&text=Pav+Bhaji",
    vegetarian: true,
    featured: false,
  },
  {
    id: "10",
    name: "Masala Chai",
    description: "Spiced Indian tea with milk",
    price: 20,
    category: "Beverages",
    image: "/placeholder.svg?height=300&width=400&text=Masala+Chai",
    vegetarian: true,
    featured: false,
  },
  {
    id: "11",
    name: "Mango Lassi",
    description: "Sweet yogurt drink with mango pulp",
    price: 50,
    category: "Beverages",
    image: "/placeholder.svg?height=300&width=400&text=Mango+Lassi",
    vegetarian: true,
    featured: false,
  },
  {
    id: "12",
    name: "Fresh Lime Soda",
    description: "Refreshing lime-based drink with soda water",
    price: 40,
    category: "Beverages",
    image: "/placeholder.svg?height=300&width=400&text=Fresh+Lime+Soda",
    vegetarian: true,
    featured: false,
  },
]

// Cart items data (initial state)
const cartItems = [
  {
    id: "1",
    name: "Masala Dosa",
    price: 80,
    quantity: 1,
  },
  {
    id: "10",
    name: "Masala Chai",
    price: 20,
    quantity: 2,
  },
]

